volumes:
  var:
  etc:

services:
  splunk:
    image: splunk/splunk:9.4
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
    ports:
      - 8000:8000
      - 8088:8088
    volumes:
      - var:/opt/splunk/var
      - etc:/opt/splunk/etc
